---
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../docker/entrypoint.sh:/app/entrypoint.sh
    entrypoint: >
      sh /app/entrypoint.sh

